### ISSUE TITLE
Implement pledge()

### ISSUE THREAD

**Issue by job** [nilsmf/rrdp#3]
As is openbsd tradition, can you put some `pledge()` calls in the right places to make this safer to use. 

This tool probably only needs `stdio`

**Comment by nilsmf** [comment]
Yep that is the plan. Thanks :)

**Comment by cjeker** [comment]
This needs more than just stdin. rpath, wpath and cpath. Also the code currently uses libcurl directly. In the long run that should probably be replaced with a fork/exec of ftp(1) or curl(1) to talk to the http server.
Unveil should also be used to make only the working directories accessible.
